BLANK_ERROR = "'{}' cannot be blank."
USER_ALREADY_EXISTS = "A user with that email already exists."
CREATED_SUCCESSFULLY = "User created successfully."
USER_NOT_FOUND = "User not found or Invalid user email."
USER_DELETED = "User deleted."
INVALID_CREDENTIALS = "Invalid credentials!"
INADEQUATE_BALANCE = "{} Balance is insufficient"
USER_NOT_AUTHORISE = "'{}' Not authorise to this resource"
USER_LOGGED_OUT = "User <id={}> successfully logged out."
